# Config file for https://travis-ci.org/
# Validate this file here - http://lint.travis-ci.org/
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

# git configs
git:
  depth: 1

# The platforms you wants to test against
os:
  - linux

sudo: false

#install:


#before_script:


script:
    - find . \( -name '*.php' \) -exec php -lf {} \;


#after_script:

#after_success:

#after_failure:


# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

# Configure email notifications
notifications:
     email:
        on_success: never
        on_failure: always
